import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Image from "next/image";

// Icons and images
import logo from "../images/shared/desktop/logo.svg";
import headphones_image from "../images/shared/desktop/image-category-thumbnail-headphones.png"
import speakers_image from "../images/shared/desktop/image-category-thumbnail-speakers.png"
import earphones_image from "../images/shared/desktop/image-category-thumbnail-earphones.png";
import speakers_home_image from "../images/home/desktop/image-speaker-zx9.png"
import zx7_speaker_image from "../images/home/desktop/image-speaker-zx7.jpg";


const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <div className={styles.firstComponent}>
          <div className={styles.innerFirstComponent}>
            <div className={styles.left}>
              <div className={styles.subHeader}>NEW PRODUCT</div>
              <div className={styles.header}>XX99 MARK II HEADPHONES</div>
              <div className={styles.text}>Experience natural, lifelike audio and exceptional build quality made for the passionate music enthusiast.</div>
              <Link href={`/products/xx99-mark-two-headphones`}><button>SEE PRODUCT</button></Link>
            </div>
          </div>
        </div>
        <div className={styles.mainComponent}>
          <div className={styles.innerMainComponent}>
            <div className={styles.first}>
              <div className={styles.card}>
                <Image src={headphones_image} width={163} height={160} alt="headphones" />
                <div className={styles.header}>HEADPHONES</div>
                <Link className={styles.link} href="/headphones">SHOP</Link>
              </div>
              <div className={styles.card}>
                <Image src={speakers_image} width={163} height={160} alt="headphones" />
                <div className={styles.header}>SPEAKERS</div>
                <Link className={styles.link} href="/speakers">SHOP</Link>
              </div>
              <div className={styles.card}>
                <Image src={earphones_image} width={163} height={160} alt="headphones" />
                <div className={styles.header}>EARPHONES</div>
                <Link className={styles.link} href="/earphones">SHOP</Link>
              </div>
            </div>
            <div className={styles.second}>
              <Image src={speakers_home_image} height={493} width={410} alt="speakers" />
              <div>
                <div className={styles.header}>ZX9 SPEAKER</div>
                <div className={styles.text}>Upgrade to premium speakers that are phenomenally built to deliver truly remarkable sound.</div>
                <Link href={"/products/zx9-speaker"}><button className={styles.button}>SEE PRODUCT</button></Link>
              </div>
            </div>
            <div className={styles.third}>
              <div className={styles.header}>ZX7 SPEAKER</div>
              <Link href={"/products/zx7-speaker"}><button className={styles.button}>SEE PRODUCT</button></Link>
            </div>
            <div className={styles.fourth}>
              <div className={styles.left}></div>
              <div className={styles.right}>
                <div className={styles.header}>YX1 EARPHONES</div>
                <Link href={"/products/yx1-earphones"}><button className={styles.button}>SEE PRODUCT</button></Link>
              </div>
            </div>
            <div className={styles.fifth}>
              <div className={styles.left}>
                <div className={styles.header}>Bringing you the <span>best</span> audio gear</div>
                <div className={styles.text}>Located at the heart of New York City, Audiophile is the premier store for high end headphones, earphones, speakers, and audio accessories. We have a large showroom and luxury demonstration rooms available for you to browse and experience a wide range of our products. Stop by our store to meet some of the fantastic people who make Audiophile the best place to buy your portable audio equipment.</div>
              </div>
              <div className={styles.right}></div>
            </div>
          </div>
        </div>
        
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className={styles.authContainer}>
      <p className={styles.showcaseText}>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className={styles.loginButton}
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
